### ISSUE TITLE
Logs are stored in nested-json format

### ISSUE THREAD

**Issue by sriram9707** [aws-samples/aws-security-hub-findings-export#1]
the raw logs after getting parsed through the lambda is stored as nested-json format. can we have the logs stored in key value pair?

**Comment by farside5** [comment]
Security Hub uses nested-json for its findings.  The json format is preserved to ensure consistency.  However, if you wish to extract fields in the finding, you can modify line 196-199 of the [securityhub_export.yml](https://github.com/aws-samples/aws-security-hub-findings-export/blob/master/securityhub_export.yml) file to change the output.
