### ISSUE TITLE
detail-type: not supported in Athena

### ISSUE THREAD

**Issue by ozbillwang** [aws-samples/aws-security-hub-findings-export#3]
I'd like to feed the finding data from s3 to aws athena via aws Glue. But Athena doesn't support minus (`-`) in table column names. 

https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html

>Special characters
>Special characters other than underscore (_) are not supported. For more information, see the Apache Hive LanguageManual DDL documentation.

Unlucky, there is one added in cloudformation template in this repo. It stop Athena to work and generate `patitioned` tables.

https://github.com/aws-samples/aws-security-hub-findings-export/blob/master/securityhub_export.yml#L50

```
        detail-type:
          - Security Hub Findings - Imported
```

The final finding output looks like this

```
{
  "version": "0",
  "id": "xxxx-e6d0-60f5-44d5-5adb9bb4761d",
  "detail-type": "Security Hub Findings - Imported",
  "source": "aws.securityhub",
  "account": "123456789012",
```

We have to change the name from `detail-type` to `detail_type` or `detailType`

**Comment by farside5** [comment]
Hi ozbillwang, thanks for the feedback.  The [deail-type at line 50](https://github.com/aws-samples/aws-security-hub-findings-export/blob/master/securityhub_export.yml#L50) is needed for event subscription.  But I've added logic in the lambda function to change 'detail-type' to 'detailType', which will ensure Athena compatibility.
