### ISSUE TITLE
can not find a proper IAM service linked role for this cloudformtion

### ISSUE THREAD

**Issue by diawyc** [aws-samples/aws-security-hub-findings-export#5]
Hello team,

would you please also share the IAM policy of the service role when you launch this cloudformation template?
We can not use fulladmin for it ,must keep the least priviledge ,I tried several times, but still fail,
"because no identity-based policy allows the iam:PassRole action(Service:Lambda, status code:403)"

Thanks.

**Comment by farside5** [comment]
If it is a PassRole exception, try to allow PassRole in your deployment role.  For example, add the following section to your deployment role.

>
    {
            "Sid": "AllowLimitedPassRole",
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": "arn:aws:iam::123456789012:role/replace_with_your_lambda_role"
    }  
>
